apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: tanzu-java-web-postgres-db
  annotations: {}
  labels:
    app.kubernetes.io/part-of: tanzu-java-web-postgres
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tanzu-java-web-postgres
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ResourceClaim
    name: db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: tanzu-java-web-postgres

